# Pythonを使ったビンゴカードとビンゴ抽選器作り
## Pythonのデータ系ライブラリ NumPy, pandasの紹介

遅くなりましたが、このnotebookは[Geek Women Advent Calendar 2017](https://qiita.com/advent-calendar/2017/geekwomenjapan) 17日目の投稿です。    
16日目はkomo_frさんの[GitHubでmatplotlibにstarをつけている人が、他にどんなリポジトリに注目しているか調べてみる](https://github.com/komo-fr/AdventCalender/blob/master/2017/GeekWomenJapanAdventCalendar2017_day16.ipynb)でした。

## 背景

先日、事務系の方にPythonの使い方を教える機会がありました。事務系と言えば、Excelだよね？ということで、Pythonのデータ分析によく使われるライブラリ、NumPy、pandasを紹介しつつ、Excelに出力するコード例を作りました。ここではそのコードを一部改変してご紹介します。

## ビンゴカードを作る

一般的なビンゴカードってどんなものだっけ？と思って調べたところ、こういう配置になっているようです。

|列名|B |I |N | G| O|
|--|--|--|--|--|--|
|値の範囲|1-15 |16-30 |31-45 |46-60 |61-75|

このルールに従ってカードを作っていきます。手順は以下の通りです。   

### 手順
1. ビンゴカード用数値セットを作成する
2. ビンゴカード風の体裁に整える

### 1. ビンゴカード用数値セットを作成する - Numpy活用例

ビンゴカードを作成します。ビンゴカード用の数値セットはNumpyを使って作ります。   
[NumPy](numpy.org)    
    
手順は以下の通りです。

#### Numpy のインポート

In [1]:
import numpy as np # numpyをインポートし、npという名前で利用します

#### 整数列の作成
NumPyを使って整数列を作成します。   

In [2]:
values_b = np.arange(1, 16)
values_i = np.arange(16, 31)
values_n = np.arange(31, 46)
values_g = np.arange(46, 61)
values_o = np.arange(61, 76)

上から順にb, i, n, g, o列用の数列になります。中身を確認してみましょう。

In [3]:
values_b, values_i, values_n, values_g, values_o

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]),
 array([46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]),
 array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75]))

それぞれの列用の整数列が作成されています。

#### 整数列リストから値をランダムに選択

ビンゴカードなので、各整数列から5つずつ値をランダムに取り出した数値セットの作成が必要です。NumPyの関数 `numpy.random.choice` を使用します。ビンゴカードの仕様として重複不可のため、`replace=False` を設定して、各整数列から5つずつ値を取り出します。

In [4]:
selected_b = np.random.choice(values_b, 5, replace=False)
selected_i = np.random.choice(values_i, 5, replace=False)
selected_n = np.random.choice(values_n, 5, replace=False)
selected_g = np.random.choice(values_g, 5, replace=False)
selected_o = np.random.choice(values_o, 5, replace=False)

取り出した値を確認します。

In [5]:
selected_b, selected_i, selected_n, selected_g, selected_o

(array([ 7,  1,  6,  4, 11]),
 array([21, 23, 19, 28, 22]),
 array([41, 39, 34, 33, 37]),
 array([57, 51, 55, 50, 48]),
 array([71, 65, 72, 61, 68]))

各列について、5つずつ値が抽出されました。

#### 値をひとつのリストにまとめる

列ごとに5つの値を取り出したので、1つにまとめます。のちのちの作業のため、NumPyのarrayとしてまとめます。

In [6]:
selected_all = np.array([selected_b, selected_i, selected_n,
                selected_g, selected_o])

In [7]:
selected_all

array([[ 7,  1,  6,  4, 11],
       [21, 23, 19, 28, 22],
       [41, 39, 34, 33, 37],
       [57, 51, 55, 50, 48],
       [71, 65, 72, 61, 68]])

selected_allにNumPy array型で数値が格納されました。

#### 行列を転置する

各列につき、5つの値を取り出して `selected_all` という変数にまとめましたが、このままでは正しいビンゴカードはできません。縦に並ぶべき数値が横に並んでいるからです。ここでもNumPyの出番です。数値の行と列を入れ替えます。NumPyを使うと`.T`をつけるだけで、行列の転置がおこなえます。

In [8]:
# 行列を転地
selected_all_t = selected_all.T

In [9]:
selected_all_t

array([[ 7, 21, 41, 57, 71],
       [ 1, 23, 39, 51, 65],
       [ 6, 19, 34, 55, 72],
       [ 4, 28, 33, 50, 61],
       [11, 22, 37, 48, 68]])

数値の行列が転置されましたね。これでビンゴカード用の数値セットの完成です。

### 2. ビンゴカード風の体裁に整える - pandas活用例

ここではpandasを使って作成した数値セットをビンゴカード風の体裁に整えていきます。

#### pandasのDataFrameに格納する

まず数値をpandasのDataFrameに格納します。

In [10]:
import pandas as pd # pandasをインポートし、pdという名前で利用します

In [11]:
df = pd.DataFrame(selected_all_t)

In [12]:
df

0   1   2   3   4
0   7  21  41  57  71
1   1  23  39  51  65
2   6  19  34  55  72
3   4  28  33  50  61
4  11  22  37  48  68

先ほどの数列がデータフレームに格納されました。

#### 行のインデックスを変更する
上記のデータフレームのインデックス（行頭のラベル、ここでは0-4の数字）がゼロから始まっていますが、ビンゴカードは通常1から5のインデックスが振られているので、1から5に振り直します。

In [13]:
df.index=np.arange(1, 6)

In [14]:
df

0   1   2   3   4
1   7  21  41  57  71
2   1  23  39  51  65
3   6  19  34  55  72
4   4  28  33  50  61
5  11  22  37  48  68

インデックスが1～5に振り直されました。

#### 列のインデックスを変更する
BINGOカードの数列の上側、列名のところは通常「B」「I」「N」「G」「O」の文字が書かれているので、列名をB、I、N、G、Oに振り直します。

In [15]:
df.columns = list('BINGO')

In [16]:
df

B   I   N   G   O
1   7  21  41  57  71
2   1  23  39  51  65
3   6  19  34  55  72
4   4  28  33  50  61
5  11  22  37  48  68

列名がB、I、N、G、Oに変換されました。なお、 `list`はPythonの組み込み関数（正確にはミュータブルなシーケンス型）で、文字列（正確にはiterable）のリストを作ることができます。

In [17]:
list('BINGO')

['B', 'I', 'N', 'G', 'O']

#### 中心の番号を文字列（'BINGO'）に置換
ところで、ビンゴカードの中心は数字が入っていないですよね。通常は「BINGO」等、文字列が入っていて、最初からオープンしていい場所となっています。ここでも3行目（インデックスが3）、N列の数値を「BINGO」に置換します。pandasの`loc`を使うと、特定の位置が選択できます。

In [18]:
df.loc[3, 'N'] = 'BINGO'

In [19]:
df

B   I      N   G   O
1   7  21     41  57  71
2   1  23     39  51  65
3   6  19  BINGO  55  72
4   4  28     33  50  61
5  11  22     37  48  68

中心（3行N列）が「BINGO」に書き換えられました。

#### ファイルに出力する
ビンゴカードの情報ができたので、ファイルに出力します。

In [20]:
# Excelに出力
fname = 'bingo_card.xlsx'
sname = 'bingo_card'
df.to_excel(fname, sheet_name=sname)

ここではExcelに出力しましたが、csvファイル等にも出力できます。    
出力したExcelファイルを印刷すれば、オリジナルビンゴカードの完成です。   
なお、もっと体裁を整えたい！と言う方は[OpenPyXL](https://openpyxl.readthedocs.io/en/default/)をご利用ください。   
Excelのセルサイズやカラーさえｍ整えることができてしまう優れもの?です。        

[OpenPyXL](https://openpyxl.readthedocs.io/en/default/)     
[\[Python\] openpyxl で Excel を操作してみた！](http://note.crohaco.net/2017/python-openpyxl-excel/)

# ビンゴ抽選機

それでは続いてビンゴ抽選器を作っていきます。手順は以下の通りです。

### 手順
1. 1から75までの整数列を生成する
2. 値をランダムに取り出す
2. 選択済み番号リストを更新する

### 1. 1から75までの整数列を生成する
1から75までの整数列を作ります。

In [21]:
values = list(range(1, 76))

**ビンゴ開始後に上記セルを実行するとvaluesがリセットされてしまいます。一度生成したら、コメントアウト（行頭に # をつける）などして、再実行しないように注意しましょう**

### 2. 値をランダムに取り出す

生成したvaluesからランダムに値を1つとりだし、値を出力する関数を作成します。値を選択したら選択された値と選択された値リストを出力します。一度選択された値が再び選ばれたら、再実行を促します。

In [22]:
def bingo():
    # valuesからランダムに値を一つ取り出す
    v = np.random.choice(values, 1)

    # 値を出力する
    if '(' in str(v[0]): # 値が抽出済みの場合再実行を促す
        print('【もう一度実行してください】')
        print('選択された値は ', v[0], ' で、選択済みでした。')
        print(values)
        
    else: # 抽出された値を出力する
        print('【選択された値は (', v[0], ') です！】')
        values[int(v[0]) - 1] = '({})'.format(str(v[0]))
        print(values)

作成した `bingo`関数を繰り返し実行すれば、ビンゴ抽選器になります！

In [23]:
#　ビンゴ抽選器
bingo()

【選択された値は ( 41 ) です！】
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, '(41)', 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75]


以上、[Geek Women Advent Calendar 2017](https://qiita.com/advent-calendar/2017/geekwomenjapan) 17日目の投稿、「Pythonを使ったビンゴカードとビンゴ抽選器作り」でした。ぜひ忘年会のお供にご活用ください。プルリクもお待ちしています！   

18日目は [@maaya8585](https://twitter.com/maaya8585) さんの[Azure Custom Vision Serviceはミッキーを判別できるのか](https://hotchpotchj37.wordpress.com/2017/12/18/azure-custom-vision-service%E3%81%AF%E3%83%9F%E3%83%83%E3%82%AD%E3%83%BC%E3%82%92%E5%88%A4%E5%88%A5%E3%81%A7%E3%81%8D%E3%82%8B%E3%81%AE%E3%81%8B/)です。  
ミッキーの顔のモデルチェンジが行われているなんて、全然知りませんでした！   